# Example command:
#   Humble on a Nvidia system:
#   DOCKER_IMAGE=humble-tutorial docker compose run gpu
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=rolling-tutorial docker compose run cpu

# IMPORTANT
# moveit2_tutorials no longer exists

# NOTE
# Try this first for learning tutorials
 
# Volume: $XAUTHORITY:/root/.Xauthority
# not all setups require .Xauthority to be explicitly managed, 
# depending on the security settings and configurations of the X server
# instead, you can disable access control using the command xhost + 

# QT_X11_NO_MITSHM: 1: This environment variable prevents the use of MIT-SHM (shared memory) 
# extension for X11, which can sometimes cause issues in Docker containers.


services:
  # cpu:
  #   image: ghcr.io/moveit/moveit2_tutorials:$DOCKER_IMAGE
  #   container_name: moveit2_container
  #   privileged: true
  #   network_mode: host
  #   command: /bin/bash
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - $XAUTHORITY:/root/.Xauthority
  #   environment:
  #     QT_X11_NO_MITSHM: 1
  #     DISPLAY: $DISPLAY
  gpu:
    image: ghcr.io/moveit/moveit2_tutorials:humble-tutorial
    container_name: moveit2_container
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: host.docker.internal:0.0
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all