FROM osrf/ros:noetic-desktop-full-focal

# Install basic development tools
RUN apt-get update && apt-get install -y \
    python3-pip \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install torch torchvision torchaudio

ENTRYPOINT ["/bin/bash"]
