# New dockerfile for the wool diameter pipeline (2024)

# Use CUDA 11.3 with Ubuntu 22.04 base image
FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

# Set the timezone
ENV TZ=Australia/Sydney
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Remove outdated repository lists if they exist
RUN rm -f /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/nvidia-ml.list

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo \
    cmake \
    wget \
    bash \
    build-essential \
    software-properties-common \
    ca-certificates \
    xvfb \
    libsm6 \
    libxrender1 \
    libfontconfig1 \
    libpython3-dev \
    libopenblas-dev \
    libxext-dev \
    libglib2.0-0 \
    libglfw3 \
    freeglut3-dev \
    git \
    vim \
    gcc \
    g++ \
    zlib1g \
    python3.10-venv \
    python3.10-dev \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*

# NOTE Still have problems relating to Cython  

# # Upgrade pip to the latest version and install Python packages
# RUN python3.10 -m pip install \
#     numpy \
#     scipy \
#     matplotlib==3.3.4 \
#     future-fstrings \
#     scikit-learn==0.24.2 \
#     tifffile==2020.9.3 \
#     Pillow==6.2.2 \
#     pypng==0.0.21 \
#     scikit-image \
#     scikit-build \
#     # Cython==0.29.10 \
#     setuptools \
#     pyyaml \
#     opencv-python==3.4.2.17 \
#     torch==1.10.0+cu113 \
#     torchvision==0.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html \
#     pycocotools

# For the newest version of Python packages
RUN python3.10 -m pip install \
    numpy \
    scipy \
    matplotlib \
    future-fstrings \
    scikit-learn \
    tifffile \
    Pillow \
    pypng \
    scikit-image \
    scikit-build \
    # Cython==0.29.10 \
    setuptools \
    pyyaml \
    opencv-python \
    torch \
    torchvision \
    pycocotools

# Clean up unnecessary files to reduce image size
RUN ldconfig && \
    apt-get clean && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* /root/.cache

# Set the entry point to bash for easier debugging and usage
ENTRYPOINT ["/bin/bash"]
