# version: '3.8' # osbsolete

services:
  wool_container:
    image: minhquanvu0604/wool_image:first_trained1.0
    container_name: wool_container
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # the number of GPU devices that should be reserved = default
              capabilities: [gpu]
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/quanvu/git/wool-estimation:/root/wool-estimation
      # - /media/quanvu/MinhQuanVu4/AWI:/root/AWI
      - /home/quanvu/uts/AWI_results/qv_segmentation_results:/root/AWI/qv_segmentation_results
    network_mode: host
    ipc: host
    stdin_open: true  # Equivalent to -i, keeps stdin open = default
    tty: true  # Equivalent to -t, allocates a TTY = default
    working_dir: /root/wool-estimation/fibre_segmentation/debug/

# cd /root/wool-estimation/fibre_segmentation/debug/

